"""Provider-agnostic batch submission adapter contracts.

Adapters implement translation from internal request payloads into provider
request formats and normalize submission responses into a shared result shape.
"""

import abc
from dataclasses import dataclass, field
from typing import Any, Dict, Mapping, Sequence, Tuple

from mmirage.config.batch_provider import BatchProviderConfig


@dataclass
class BatchSubmissionResult:
    """Normalized result returned by any provider adapter after chunk submission.

    Attributes:
        provider_batch_id: Provider-side identifier for the submitted job/batch.
        status: Provider submission status normalized to a short string.
        submitted_request_count: Number of requests accepted in this submission.
        raw_response: Original provider response payload for traceability.
    """

    provider_batch_id: str
    status: str
    submitted_request_count: int
    raw_response: Mapping[str, Any] = field(default_factory=dict)


class BatchSubmissionAdapter(abc.ABC):
    """Abstract interface for provider-specific batch submission adapters.

    Implementations should be deterministic for request building and byte
    estimation so chunk boundaries can be reproduced across retries.
    """

    required_credentials: Tuple[str, ...] = tuple()

    @property
    @abc.abstractmethod
    def adapter_name(self) -> str:
        """Return a stable adapter identity string.

        The identity should remain stable across code changes that preserve
        behavior and should change only when semantics diverge.
        """
        raise NotImplementedError()

    @property
    @abc.abstractmethod
    def adapter_version(self) -> str:
        """Return the adapter implementation version.

        This value is persisted in metadata artifacts to support auditing and
        replay diagnostics across code revisions.
        """
        raise NotImplementedError()

    @abc.abstractmethod
    def build_request(
        self,
        custom_id: str,
        payload: Mapping[str, Any],
        config: BatchProviderConfig,
    ) -> Mapping[str, Any]:
        """Build a single provider-ready request object.

        Args:
            custom_id: Stable request identifier used to map async results back
                to source rows.
            payload: Provider-neutral request payload assembled by the core
                processing layer.
            config: Provider configuration contract that may influence request
                shaping.

        Returns:
            A provider-specific request object represented as a mapping.
        """
        raise NotImplementedError()

    @abc.abstractmethod
    def estimate_request_bytes(self, request: Mapping[str, Any]) -> int:
        """Estimate serialized UTF-8 bytes for a request payload.

        The estimate must match or safely upper-bound the size produced by the
        serializer used for submission so chunk boundaries are enforced
        correctly.

        Args:
            request: Provider request object returned by ``build_request``.

        Returns:
            Estimated byte size for the serialized request.
        """
        raise NotImplementedError()

    @abc.abstractmethod
    def submit_chunk(
        self,
        chunk_id: str,
        requests: Sequence[Mapping[str, Any]],
        config: BatchProviderConfig,
    ) -> Mapping[str, Any]:
        """Submit one pre-chunked request group to the provider.

        Args:
            chunk_id: Internal chunk identifier generated by orchestration.
            requests: Provider-ready request objects belonging to this chunk.
            config: Provider config containing credentials and submission knobs.

        Returns:
            Raw provider response payload as a mapping.
        """
        raise NotImplementedError()

    @abc.abstractmethod
    def parse_submission_result(
        self,
        raw_result: Mapping[str, Any],
        request_count: int,
    ) -> BatchSubmissionResult:
        """Normalize provider submission output into a shared result model.

        Args:
            raw_result: Raw payload returned by ``submit_chunk``.
            request_count: Number of requests submitted in the chunk.

        Returns:
            A normalized ``BatchSubmissionResult`` for provider-neutral
            orchestration and metadata persistence.
        """
        raise NotImplementedError()
