FROM docker.io/python:3.12-slim

COPY pyproject.toml README.md /workspace/MMIRAGE/
WORKDIR /workspace/MMIRAGE

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

COPY . .

RUN pip install --no-cache-dir .

ENTRYPOINT ["/bin/bash"]
