#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ANONLIB_PATH=$(cd -- "${SCRIPT_DIR}/.." && pwd)
OUTPUT_PATH="${ANONLIB_PATH}/.env"

cat >"${OUTPUT_PATH}" <<EOF
# Generated by scripts/generate_env.sh
ANONLIB_PATH="${ANONLIB_PATH}"
EOF

printf 'Created %s\n' "${OUTPUT_PATH}"
