"""Configuration for the custom processor."""

from dataclasses import dataclass
from typing import Any, Literal, Optional, Sequence

from mmirage.core.process.base import BaseProcessorConfig, ProcessorRegistry
from mmirage.core.process.variables import BaseVar, OutputVar


@dataclass
class CustomProcessorConfig(BaseProcessorConfig):
    """Configuration for executing a user-provided Python function."""

    type: Literal["custom"] = "custom"
    script_path: str = ""
    function_name: str = ""
    max_workers: int = 1
    timeout_ms: Optional[int] = None
    max_timeouts: int = 1
    max_errors: int = 1
    fallback_value: Any = None
    start_method: Literal["spawn", "fork", "forkserver"] = "spawn"

    def __post_init__(self) -> None:
        self.script_path = self.script_path.strip()
        self.function_name = self.function_name.strip()

        if not self.script_path:
            raise ValueError("script_path must be a non-empty string")
        if not self.function_name:
            raise ValueError("function_name must be a non-empty string")
        if self.max_workers < 1:
            raise ValueError("max_workers must be >= 1")
        if self.timeout_ms is not None and self.timeout_ms < 1:
            raise ValueError("timeout_ms must be >= 1, or unset to disable the timeout")
        if self.max_timeouts < 1:
            raise ValueError("max_timeouts must be >= 1")
        if self.max_errors < 1:
            raise ValueError("max_errors must be >= 1")


@dataclass
class CustomOutputVar(OutputVar):
    """Output variable generated by the custom processor."""

    type: str = "custom"

    def is_computable(self, vars: Sequence[BaseVar]) -> bool:
        return True


ProcessorRegistry.register_types("custom", CustomProcessorConfig, CustomOutputVar)
